name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip

      - name: Install Python module development requirements
        run: |
          python3 -m pip install pytest coverage

      - name: Install
        run: |
          python3 -m pip install .

      - name: Run tests
        run: |
          python3 -m pytest

      - name: Calculate coverage
        run: |
          python3 -m coverage run --branch --include="exputil/*" -m pytest
          python3 -m coverage xml
          python3 -m coverage html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
